# Generated by Django 4.1.1 on 2022-10-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('costitem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockquantity', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
